### ISSUE TITLE
Terminal options are unknown

### ISSUE THREAD

**Issue by toupeira** [dbakker/vim-lint#1]
I get an error "Unknown option" for settings like `t_vb`, would be great to add support for these (see `:help terminal-options`).

**Comment by dbakker** [comment]
Thank you, nice catch. This should fix it!

**Comment by toupeira** [comment]
Indeed it does, thanks!

**Comment by toupeira** [comment]
Another related issue: inline comments after `set` are treated as options, so for example the following:

```
set t_vb= " disable bells
```

will raise an error `Unknown option "" disable bells"`
