### ISSUE TITLE
MacVim options and commands

### ISSUE THREAD

**Issue by kusnier** [dbakker/vim-lint#2]
Can you add detection for MacVim and allow following options and commands?

> These are the non-standard options that MacVim supports:
>     'antialias' 'fullscreen'        'fuoptions'
>     'macmeta'   'toolbariconsize'   'transparency'
> 
> These are the non-standard commands that MacVim supports:
>     |:macaction|    |:macmen

You can detect MacVim with `has("gui_macvim")`
More: http://code.google.com/p/macvim/source/browse/trunk/runtime/doc/gui_mac.txt

**Comment by dbakker** [comment]
Thank you. I've added detection for the options and commands you suggested. Please check I set the correct datatype for the options. I'll assume for now that mac specific options are legal and people have somehow guarded them themselves.

**Comment by kusnier** [comment]
Hi,

`macmeta` has a wrong datatype. The type should be `boolean`.

Thanks.
